// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['app']['App']['AppInfo']();
}

export function ConvertClipboardMarkdownToTable() {
  return window['go']['app']['App']['ConvertClipboardMarkdownToTable']();
}

export function ConvertClipboardTableToMarkdown() {
  return window['go']['app']['App']['ConvertClipboardTableToMarkdown']();
}

export function ConvertMarkdownTableToTSV(arg1) {
  return window['go']['app']['App']['ConvertMarkdownTableToTSV'](arg1);
}

export function ConvertStructuredToTable(arg1, arg2) {
  return window['go']['app']['App']['ConvertStructuredToTable'](arg1, arg2);
}

export function CopyMarkdownTableToClipboard(arg1) {
  return window['go']['app']['App']['CopyMarkdownTableToClipboard'](arg1);
}

export function CurrentWorkingDirectory() {
  return window['go']['app']['App']['CurrentWorkingDirectory']();
}

export function GetStructuredTableRules() {
  return window['go']['app']['App']['GetStructuredTableRules']();
}

export function GetViewerConfig() {
  return window['go']['app']['App']['GetViewerConfig']();
}

export function ListAWSProfiles() {
  return window['go']['app']['App']['ListAWSProfiles']();
}

export function ListLocalArchive(arg1, arg2) {
  return window['go']['app']['App']['ListLocalArchive'](arg1, arg2);
}

export function ListLocalDirectory(arg1) {
  return window['go']['app']['App']['ListLocalDirectory'](arg1);
}

export function ListS3Archive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListS3Archive'](arg1, arg2, arg3, arg4, arg5);
}

export function ListS3Buckets(arg1, arg2) {
  return window['go']['app']['App']['ListS3Buckets'](arg1, arg2);
}

export function ListS3Directory(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListS3Directory'](arg1, arg2, arg3, arg4);
}

export function ParentLocalDirectory(arg1) {
  return window['go']['app']['App']['ParentLocalDirectory'](arg1);
}

export function ReadLocalArchivePreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadLocalArchivePreview'](arg1, arg2, arg3);
}

export function ReadLocalPreview(arg1, arg2) {
  return window['go']['app']['App']['ReadLocalPreview'](arg1, arg2);
}

export function ReadLocalTextFile(arg1) {
  return window['go']['app']['App']['ReadLocalTextFile'](arg1);
}

export function ReadS3ArchivePreview(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['ReadS3ArchivePreview'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReadS3Preview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ReadS3Preview'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectLocalDirectory() {
  return window['go']['app']['App']['SelectLocalDirectory']();
}

export function UpdateStructuredTableRules(arg1) {
  return window['go']['app']['App']['UpdateStructuredTableRules'](arg1);
}

export function UpdateViewerConfig(arg1) {
  return window['go']['app']['App']['UpdateViewerConfig'](arg1);
}
