// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AppInfo():Promise<string>;

export function ConvertStructuredToTable(arg1:string,arg2:string):Promise<app.StructuredTable>;

export function CurrentWorkingDirectory():Promise<string>;

export function GetStructuredTableRules():Promise<Array<app.StructuredTableRule>>;

export function GetViewerConfig():Promise<app.ViewerConfig>;

export function ListAWSProfiles():Promise<Array<string>>;

export function ListLocalArchive(arg1:string,arg2:string):Promise<Array<app.LocalEntry>>;

export function ListLocalDirectory(arg1:string):Promise<Array<app.LocalEntry>>;

export function ListS3Archive(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<app.LocalEntry>>;

export function ListS3Buckets(arg1:string,arg2:string):Promise<Array<app.LocalEntry>>;

export function ListS3Directory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<app.LocalEntry>>;

export function ParentLocalDirectory(arg1:string):Promise<string>;

export function ReadLocalArchivePreview(arg1:string,arg2:string,arg3:string):Promise<app.S3Preview>;

export function ReadLocalPreview(arg1:string,arg2:string):Promise<app.S3Preview>;

export function ReadLocalTextFile(arg1:string):Promise<string>;

export function ReadS3ArchivePreview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<app.S3Preview>;

export function ReadS3Preview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<app.S3Preview>;

export function SelectLocalDirectory():Promise<string>;

export function UpdateStructuredTableRules(arg1:Array<app.StructuredTableRule>):Promise<void>;

export function UpdateViewerConfig(arg1:app.ViewerConfig):Promise<void>;
